//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mappalachia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mappalachia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT x, y, z
        ///FROM Position_Data
        ///WHERE spaceFormID = $spaceFormID
        ///.
        /// </summary>
        internal static string getAllCoordsSpace {
            get {
                return ResourceManager.GetString("getAllCoordsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT mapMarkerName FROM Map_Markers;.
        /// </summary>
        internal static string getAllUniqueMapMarkers {
            get {
                return ResourceManager.GetString("getAllUniqueMapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT z
        ///FROM Position_Data
        ///WHERE spaceFormID = $spaceFormID
        ///.
        /// </summary>
        internal static string getAllZCoordsSpace {
            get {
                return ResourceManager.GetString("getAllZCoordsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT x, y, z, chance as chance
        ///FROM NPC_Search WHERE NPC = $npc and chance &gt;= $chance and spaceFormID = $spaceFormID
        ///ORDER BY z ASC
        ///.
        /// </summary>
        internal static string getCoordsNPC {
            get {
                return ResourceManager.GetString("getCoordsNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT regionNum, coordNum, x, y FROM Region
        ///WHERE regionFormID = $regionFormID AND Region.spaceFormID = $spaceFormID
        ///.
        /// </summary>
        internal static string getCoordsRegion {
            get {
                return ResourceManager.GetString("getCoordsRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT x, y, z, magnitude FROM Scrap_Search
        ///WHERE component = $scrap AND Scrap_Search.spaceFormID = $spaceFormID
        ///ORDER BY z ASC
        ///.
        /// </summary>
        internal static string getCoordsScrap {
            get {
                return ResourceManager.GetString("getCoordsScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT x, y, z, primitiveShape, boundX, boundY, boundZ, rotZ
        ///FROM Position_Data
        ///WHERE spaceFormID = $spaceFormID AND referenceFormID = $formID AND lockLevel IN ($allowedLockTypes) AND label = $label
        ///ORDER BY z ASC
        ///.
        /// </summary>
        internal static string getCoordsStandard {
            get {
                return ResourceManager.GetString("getCoordsStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT version FROM Game_Version LIMIT 1;
        ///.
        /// </summary>
        internal static string getGameVersion {
            get {
                return ResourceManager.GetString("getGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT lockLevel
        ///FROM Lock_Levels
        ///.
        /// </summary>
        internal static string getLockLevels {
            get {
                return ResourceManager.GetString("getLockLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT label, mapMarkerName, x, y FROM Map_Markers WHERE spaceFormID = $spaceFormID;
        ///.
        /// </summary>
        internal static string getMapMarkers {
            get {
                return ResourceManager.GetString("getMapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT NPC FROM NPC_Search
        ///ORDER BY NPC ASC
        ///.
        /// </summary>
        internal static string getNPCTypes {
            get {
                return ResourceManager.GetString("getNPCTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT component FROM Scrap_Search
        ///.
        /// </summary>
        internal static string getScrapTypes {
            get {
                return ResourceManager.GetString("getScrapTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT signature
        ///FROM Entity_Info
        ///.
        /// </summary>
        internal static string getSignatures {
            get {
                return ResourceManager.GetString("getSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT spaceFormID, spaceEditorID, spaceDisplayName, isWorldspace, xCenter, yCenter, xMin, xMax, yMin, yMax, nudgeX, nudgeY, nudgeScale
        ///FROM Space_Info
        ///ORDER BY isWorldspace DESC, spaceDisplayName
        ///.
        /// </summary>
        internal static string getSpaces {
            get {
                return ResourceManager.GetString("getSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT NPC, MIN(chance) as chance, COUNT(*), spaceEditorId, spaceDisplayName
        ///FROM NPC_Search
        ///INNER JOIN Space_Info ON NPC_Search.spaceFormId = Space_Info.spaceFormID
        ///WHERE NPC = $npc and chance &gt;= $chance and NPC_Search.spaceFormId = $spaceFormID
        ///.
        /// </summary>
        internal static string searchNPC {
            get {
                return ResourceManager.GetString("searchNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT NPC, MIN(chance) as chance, COUNT(*) as amount, spaceEditorId, spaceDisplayName
        ///FROM NPC_Search
        ///INNER JOIN Space_Info ON NPC_Search.spaceFormId = Space_Info.spaceFormID
        ///WHERE NPC = $npc and chance &gt;= $chance
        ///GROUP BY spaceEditorId
        ///ORDER BY NPC_Search.spaceFormID = $spaceFormID DESC, amount DESC
        ///.
        /// </summary>
        internal static string searchNPCEverywhere {
            get {
                return ResourceManager.GetString("searchNPCEverywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT regionFormID, regionEditorId, spaceEditorId, spaceDisplayName
        ///FROM Region
        ///INNER JOIN Space_Info ON Region.spaceFormID = Space_Info.spaceFormID
        ///WHERE (regionEditorId LIKE $searchTerm ESCAPE &apos;\&apos; OR regionFormID LIKE $searchTerm ESCAPE &apos;\&apos;) AND Region.spaceFormID = $spaceFormID
        ///GROUP BY regionFormID, spaceEditorID.
        /// </summary>
        internal static string searchRegion {
            get {
                return ResourceManager.GetString("searchRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT regionFormID, regionEditorId, spaceEditorId, spaceDisplayName
        ///FROM Region
        ///INNER JOIN Space_Info ON Region.spaceFormID = Space_Info.spaceFormID
        ///WHERE regionEditorId LIKE $searchTerm ESCAPE &apos;\&apos; OR regionFormID LIKE $searchTerm ESCAPE &apos;\&apos;
        ///GROUP BY regionFormID, spaceEditorID
        ///ORDER BY Region.spaceFormID = $spaceFormID DESC
        ///.
        /// </summary>
        internal static string searchRegionEverywhere {
            get {
                return ResourceManager.GetString("searchRegionEverywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT component, SUM(magnitude), COUNT(*), spaceEditorId, spaceDisplayName
        ///FROM Scrap_Search
        ///INNER JOIN Space_Info ON Scrap_Search.spaceFormID = Space_Info.spaceFormID
        ///WHERE component = $scrap AND Scrap_Search.spaceFormID = $spaceFormID
        ///.
        /// </summary>
        internal static string searchScrap {
            get {
                return ResourceManager.GetString("searchScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT component, SUM(magnitude) as amount, COUNT(*), spaceEditorId, spaceDisplayName
        ///FROM Scrap_Search
        ///INNER JOIN Space_Info ON Scrap_Search.spaceFormID = Space_Info.spaceFormID
        ///WHERE component = $scrap
        ///GROUP BY spaceEditorId
        ///ORDER BY Scrap_Search.spaceFormID = $spaceFormID DESC, amount DESC
        ///.
        /// </summary>
        internal static string searchScrapEverywhere {
            get {
                return ResourceManager.GetString("searchScrapEverywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT referenceFormId, editorID, displayName, category, lockLevel, amount, spaceEditorId, spaceDisplayName, label
        ///FROM Standard_Search
        ///JOIN Space_Info ON Standard_Search.spaceFormId = Space_Info.spaceFormID
        ///JOIN Entity_Info ON Standard_Search.referenceFormID = Entity_Info.entityFormID
        ///WHERE
        ///(category IN ($allowedSignatures) AND
        ///lockLevel IN ($allowedLockTypes) AND
        ///(EditorId LIKE $searchTerm ESCAPE &apos;\&apos; OR displayName LIKE $searchTerm ESCAPE &apos;\&apos; OR referenceFormId LIKE $searchTerm ESCAPE &apos;\&apos; OR label  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string searchStandard {
            get {
                return ResourceManager.GetString("searchStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT referenceFormId, editorID, displayName, category, lockLevel, amount, spaceEditorId, spaceDisplayName, label
        ///FROM Standard_Search
        ///JOIN Space_Info ON Standard_Search.spaceFormId = Space_Info.spaceFormID
        ///JOIN Entity_Info ON Standard_Search.referenceFormID = Entity_Info.entityFormID
        ///WHERE
        ///(category IN ($allowedSignatures) AND
        ///lockLevel IN ($allowedLockTypes) AND
        ///(EditorId LIKE $searchTerm ESCAPE &apos;\&apos; OR displayName LIKE $searchTerm ESCAPE &apos;\&apos; OR referenceFormId LIKE $searchTerm ESCAPE &apos;\&apos; OR label  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string searchStandardEverywhere {
            get {
                return ResourceManager.GetString("searchStandardEverywhere", resourceCulture);
            }
        }
    }
}
