name: Publish

on:
  push:
    branches: [ "SignTest" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish
      run: dotnet publish Mappalachia/Mappalachia.csproj -p:PublishProfile=PublishProfile.pubxml -p:SolutionDir="${{ github.workspace }}\\"

    - name: Artifact (Unsigned)
      id: upload-unsigned-artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mappalachia_Publish_Unsigned
        path: ./Mappalachia/publish/

    - name: Submit to SignPath
      uses: signpath/github-action-submit-signing-request@v2
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: 'a23cbdf3-167a-4730-a806-764a58de08d1'
        project-slug: 'Mappalachia'
        signing-policy-slug: 'test-signing'
        github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
        wait-for-completion: true
        output-artifact-directory: './Mappalachia/publish-signed/'

    - name: Artifact (Signed)
      uses: actions/upload-artifact@v4
      with:
        name: Mappalachia_Publish_Signed
        path: ./Mappalachia/publish-signed/